#!/bin/sh -e

# Make sure the folders exist
mkdir -p ${SNAP_COMMON}/config
mkdir -p ${SNAP_COMMON}/maps

. ${SNAP}/usr/bin/reset_config.sh

# set default configuration values
snapctl set simulation=false
snapctl set slam-config="${SNAP_COMMON}/config/slam_params.yaml"
snapctl set navigation-config="${SNAP_COMMON}/config/nav2_params.yaml"
snapctl set localization-config="${SNAP_COMMON}/config/localization_params.yaml"
snapctl set map="${SNAP_COMMON}/maps/current_map.yaml"

if ! snapctl is-connected ros-humble; then
  logger -t ${SNAP_NAME} "Plug 'ros-humble' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-humble <providing-snap>"
fi
